### ISSUE TITLE
【SimpleX】Reproduce Log for Light-GCN-CCL

### ISSUE THREAD

**Issue by coderaBruce** [reczoo/RecZoo#35]
Hi @kyriemao,

I am not sure if this is the right place to post my questions.
You mentioned in SimpleX paper table 3 that LGCN-CCL for AmazonBooks' performance are: R@20 0.0528 and N@20 0.0416. But training logs are only provided for MF-CCL.  For reproducibility, could you please open-source your LGCN-CCL training-log and its hyper params?

Thanks

**Comment by zhujiem** [comment]
Sorry that our other logs have been deleted during the server system updates. @kyriemao  Do you remember the hyper-params? @coderaBruce  Which hyper-parameter do you want?

**Comment by kyriemao** [comment]
Sorry, I didn't remember the hyperparams for LightGCN-CCL. But it should not be a normal setting.
