### ISSUE TITLE
[Simplex] What is the best command to reproduce LightGCN-CCL and YouTubeNet-CCL?

### ISSUE THREAD

**Issue by mgulcin** [reczoo/RecZoo#38]
Hello, 
I want to reproduce results for  LightGCN-CCL  and YouTubeNet-CCL. 
What is the best way? Which command should I use?

**Comment by zhujiem** [comment]
You can refer the YouTubeNet here and modify the loss in the config: https://github.com/reczoo/RecBox/tree/v0.0.3/model_zoo/YouTubeNet

Currently we did not provide LightGCN-CCL.
